### ISSUE TITLE
Not able to find libgumbo.so.1

### ISSUE THREAD

**Issue by MadcapJake** [Skarsnik/perl6-gumbo#2]
I get an error installing this (during tests) that it cannot located the so file.

Mine is located in `/usr/local/lib/libgumbo.so.1`.  So I cloned this repo and replaced the `LIB` tuple with a sub returning that absolute path and the module works now!

Not sure what the solution is for this, but I'm pretty sure it's not cloning and editing source :stuck_out_tongue_closed_eyes: .

**Comment by Skarsnik** [comment]
Hm, you don't have /usr/local/lib on your path ld search for? You could have set LD_LIBRARY_PATH for it. But I will add a ENV var to be able to put the location gumbo will search for.

**Comment by Skarsnik** [comment]
Fixed a long time ago.
