### ISSUE TITLE
Exceptions on testing

### ISSUE THREAD

**Issue by Altai-man** [Skarsnik/perl6-gumbo#4]
On fresh rakudo:
```
➜  ~ perl6 --version
This is Rakudo version 2016.12-201-g528ec53 built on MoarVM version 2016.12-60-g36f3385
implementing Perl 6.c.
```
The package can not be installed:
```
➜  ~ zef install Gumbo
===> Searching for: Gumbo
...
# XML part is skipped.
...
===> Testing: Gumbo:auth('Sylvain Colinet')
Could not find symbol '&Document'
  in block <unit> at t/01_basic.t line 22

Actually thrown at:
  in block <unit> at t/01_basic.t line 22

t/01_basic.t .... All 5 subtests passed 
t/02_filters.t .. ok 
Could not find symbol '&Document'
  in block <unit> at t/03_stats.t line 22

Actually thrown at:
  in block <unit> at t/03_stats.t line 22

t/03_stats.t .... All 8 subtests passed 
All tests successful.

Test Summary Report
-------------------
t/01_basic.t  (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: Bad plan.  You planned 5 tests but ran 0.
t/03_stats.t  (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: Bad plan.  You planned 8 tests but ran 0.
Files=3, Tests=5,  7 wallclock secs
Result: FAILED
===> Testing [FAIL]: Gumbo:auth('Sylvain Colinet')
```

It may be related to latest changes with import scoping, since package doesn't export `Document` now, but I'm not sure.

**Comment by Skarsnik** [comment]
I see. the use XML in Gumbo does not export the types XML provide now? Can you point me with possible solutions  (if it was already discussed/proposed)

**Comment by Altai-man** [comment]
@Skarsnik, I'm really not sure it is this particular reason, but http://rakudo.org/2016/12/17/lexical-module-loading/ can be useful in further research.
The article is written about future release of January 2017, but after I added `use XML` into first and third test files the installation was fixed.

I can send a pull request if needed.

**Comment by Skarsnik** [comment]
Fixed with https://github.com/Skarsnik/perl6-gumbo/commit/e5f1edf6e34b557fd72fe2cfe460441686e39b3b
