### ISSUE TITLE
Heap corruption

### ISSUE THREAD

**Issue by AlexDaniel** [Skarsnik/perl6-gumbo#5]
I've filed [this RT ticket](https://rt.perl.org/Ticket/Display.html?id=131003), but given that this module is completely useless with the bug, I thought I'd create an issue here as well.

**Comment by AlexDaniel** [comment]
Using libgumbo 0.10.1+dfsg-2.1 (from debian packages)

**Comment by kazcw** [comment]
There's also a bug for this in the MoarVM tracker: MoarVM/MoarVM#800.

I can attest that this is still a killer with the [current](https://github.com/kazcw/nixies/tree/bc75a3afcb680a90c7e529964f2a6131460c8f45/perl6.nix) (git) versions of moar/nqp/rakudo/perl6-gumbo and libgumbo 0.10.1. Now that my scraper has become complex enough I've started hitting this, I am trying to find some kind of workaround before I resort to restarting my whole project in another language.

**Comment by AlexDaniel** [comment]
@kazcw one of the workarounds that I use is to make things restartable. That is, the script keeps walking until it dies, then it is automatically restarted. Once it starts up, it just continues the work instead of starting from scratch.

Another thing that works is if you load a python module using Inline::Python (so instead of using the perl6 gumbo module just use whatever alternative you like in python). It works just fine.

**Comment by Skarsnik** [comment]
Maybe you can workaround with fork now? But seriously I wish someone more knowledgeable look at this issue to fix it :(

**Comment by kazcw** [comment]
Something's up with the CUnions. I'm still trying to get to the root of it. I implemented a workaround in #10.

**Comment by kazcw** [comment]
I fixed Moar, but the workaround is of course still necessary for Gumbo to be usable on the current release (mvm 2019.05)

**Comment by AlexDaniel** [comment]
holy fucking shit!!! I'll try to test this asap…

**Comment by AlexDaniel** [comment]
Oh, I forgot to reply. But yes, it does work now!

**Comment by Skarsnik** [comment]
closing I guess?

**Comment by AlexDaniel** [comment]
Yep.
